# Generated by Django 4.2.16 on 2026-07-07 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de la cita')),
                ('hora', models.TimeField(verbose_name='Hora de inicio')),
                ('estado', models.CharField(choices=[('PENDIENTE_PAGO', 'Pendiente de pago'), ('EN_REVISION', 'En revisión'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada')], db_index=True, default='PENDIENTE_PAGO', max_length=20, verbose_name='Estado')),
                ('comprobante_pago', models.FileField(blank=True, help_text='Captura/PDF de la transferencia bancaria. Máximo 5MB. Formatos: PDF, JPG, PNG.', null=True, upload_to='comprobantes/', verbose_name='Comprobante de pago')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Creada el')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Actualizada el')),
                ('fecha_transaccion', models.DateTimeField(blank=True, help_text='Fecha en que el paciente realizó la transferencia.', null=True, verbose_name='Fecha de transacción')),
                ('notas_admin', models.TextField(blank=True, verbose_name='Notas del administrador')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['fecha', 'hora'],
            },
        ),
    ]
