# Generated by Django 4.2.16 on 2026-07-07 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'rol': 'ODONTOLOGO'}, on_delete=django.db.models.deletion.PROTECT, related_name='citas_como_doctor', to=settings.AUTH_USER_MODEL, verbose_name='Odontólogo'),
        ),
        migrations.AddField(
            model_name='cita',
            name='paciente',
            field=models.ForeignKey(limit_choices_to={'rol': 'PACIENTE'}, on_delete=django.db.models.deletion.PROTECT, related_name='citas_como_paciente', to=settings.AUTH_USER_MODEL, verbose_name='Paciente'),
        ),
        migrations.AddConstraint(
            model_name='cita',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'CONFIRMADA')), fields=('doctor', 'fecha', 'hora'), name='unique_cita_confirmada_doctor'),
        ),
        migrations.AddConstraint(
            model_name='cita',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'CANCELADA'), _negated=True), fields=('paciente', 'fecha', 'hora'), name='unique_cita_activa_paciente'),
        ),
    ]
