# Generated by Django 4.2.16 on 2026-07-08 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='atendida',
            field=models.BooleanField(default=False, help_text='Marca si la cita ya fue atendida por el odontólogo.', verbose_name='Atendida'),
        ),
    ]
