# Generated by Django 4.2.16 on 2026-07-07 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True, verbose_name='Fecha de la consulta')),
                ('diagnostico', models.TextField(help_text='Descripción clínica del estado dental del paciente.', verbose_name='Diagnóstico')),
                ('tratamiento_realizado', models.TextField(help_text='Descripción del procedimiento ejecutado en la consulta.', verbose_name='Tratamiento realizado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones adicionales')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'Historial clínico',
                'verbose_name_plural': 'Historiales clínicos',
                'ordering': ['-fecha'],
            },
        ),
    ]
