# Generated by Django 4.2.16 on 2026-07-07 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fichas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialclinico',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'rol': 'ODONTOLOGO'}, on_delete=django.db.models.deletion.PROTECT, related_name='fichas_atendidas', to=settings.AUTH_USER_MODEL, verbose_name='Odontólogo tratante'),
        ),
        migrations.AddField(
            model_name='historialclinico',
            name='paciente',
            field=models.ForeignKey(limit_choices_to={'rol': 'PACIENTE'}, on_delete=django.db.models.deletion.PROTECT, related_name='historial_clinico', to=settings.AUTH_USER_MODEL, verbose_name='Paciente'),
        ),
    ]
