# Generated by Django 4.2.16 on 2026-07-08 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_cita_atendida'),
        ('fichas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialclinico',
            name='cita',
            field=models.ForeignKey(blank=True, help_text='Referencia opcional a la cita atendida.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas_clinicas', to='citas.cita', verbose_name='Cita relacionada'),
        ),
    ]
