# Generated by Django 4.2.16 on 2026-07-07 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiaBloqueado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha bloqueada')),
                ('motivo', models.CharField(help_text='Ej: Vacaciones, Feriado Nacional, Ausencia médica.', max_length=255, verbose_name='Motivo del bloqueo')),
            ],
            options={
                'verbose_name': 'Día bloqueado',
                'verbose_name_plural': 'Días bloqueados',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='HorarioTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Día de la semana')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de fin')),
            ],
            options={
                'verbose_name': 'Horario de trabajo',
                'verbose_name_plural': 'Horarios de trabajo',
                'ordering': ['dia_semana', 'hora_inicio'],
            },
        ),
    ]
