# Generated by Django 4.2.16 on 2026-07-07 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariotrabajo',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'rol': 'ODONTOLOGO'}, on_delete=django.db.models.deletion.CASCADE, related_name='horarios_trabajo', to=settings.AUTH_USER_MODEL, verbose_name='Odontólogo'),
        ),
        migrations.AddField(
            model_name='diabloqueado',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'rol': 'ODONTOLOGO'}, on_delete=django.db.models.deletion.CASCADE, related_name='dias_bloqueados', to=settings.AUTH_USER_MODEL, verbose_name='Odontólogo'),
        ),
        migrations.AlterUniqueTogether(
            name='horariotrabajo',
            unique_together={('doctor', 'dia_semana', 'hora_inicio')},
        ),
        migrations.AlterUniqueTogether(
            name='diabloqueado',
            unique_together={('doctor', 'fecha')},
        ),
    ]
