name: CI/CD — Consultorio Dental DentalCare

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: 'dentalcare-pro-web'
  PYTHON_VERSION: '3.10'

jobs:
  # JOB 1: PRUEBAS AUTOMATIZADAS CONTRA BASE DE DATOS REAL (MANDATO PROFESOR)
  test:
    runs-on: ubuntu-latest
    
    # Configuración del motor de base de datos relacional dentro del Runner
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: dentalcare_test
          POSTGRES_USER: david
          POSTGRES_PASSWORD: secretpassword123
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U david -d dentalcare_test"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Descargar Código del Repositorio
        uses: actions/checkout@v4

      - name: Configurar Entorno de Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Instalar Dependencias del Manifiesto
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar Pruebas de Integración (Inserciones y Persistencia)
        env:
          DB_ENGINE: django.db.backends.postgresql
          DB_NAME: dentalcare_test
          DB_USER: david
          DB_PASSWORD: secretpassword123
          DB_HOSTNAME: localhost
          DB_PORT: 5432
          PGSSLMODE: disable       # Evita que psycopg2 exija SSL al contenedor local
          DB_SSLMODE: disable      # Apaga de forma segura el sslmode en settings.py
          SECRET_KEY: test_secret_key_ci_cd
          DEBUG: 'True'
          # Variable corregida para que el test pueda arrancar
          AZURE_CONNECTION_STRING: ${{ secrets.AZURE_CONNECTION_STRING }}
        run: |
          python manage.py test

  # JOB 2: DESPLIEGUE EN PRODUCCIÓN (CONDICIONADO AL ÉXITO DE LAS PRUEBAS)
  deploy:
    runs-on: ubuntu-latest
    needs: test # ← CONDICIONAL CRÍTICO: Si el job 'test' falla, el despliegue se bloquea.
    
    steps:
      - name: Descargar Código del Repositorio
        uses: actions/checkout@v4

      # Login con las credenciales (Azure Login) usando el secreto AZURE_CREDENTIALS
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Despliegue en Azure App Service
      - name: Desplegar Aplicación en Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: .
